// Dữ liệu sản phẩm cho tất cả các trang - Mảng phẳng
const productsData = [
    // ===== QUẦN (73-108) =====
    {id: 73, name: 'Quần Bóng Đá Nike', price: 350000, category: 'quan', sport: 'bongda', image: '../img/tk1.jpg'},
    {id: 74, name: 'Quần Bóng Đá Adidas', price: 320000, category: 'quan', sport: 'bongda', image: '../img/tk1.jpg'},
    {id: 75, name: 'Quần Bóng Đá Puma', price: 330000, category: 'quan', sport: 'bongda', image: '../img/tk1.jpg'},
    {id: 76, name: 'Quần Manchester United', price: 480000, category: 'quan', sport: 'bongda', image: '../img/tk1.jpg'},
    {id: 77, name: 'Quần Liverpool', price: 490000, category: 'quan', sport: 'bongda', image: '../img/tk1.jpg'},
    {id: 78, name: 'Quần Real Madrid', price: 490000, category: 'quan', sport: 'bongda', image: '../img/tk1.jpg'},
    {id: 79, name: 'Quần Bóng Rổ Nike', price: 360000, category: 'quan', sport: 'bongro', image: '../img/tk1.jpg'},
    {id: 80, name: 'Quần Bóng Rổ Adidas', price: 340000, category: 'quan', sport: 'bongro', image: '../img/tk1.jpg'},
    {id: 81, name: 'Quần Bóng Rổ Spalding', price: 370000, category: 'quan', sport: 'bongro', image: '../img/tk1.jpg'},
    {id: 82, name: 'Quần Lakers', price: 500000, category: 'quan', sport: 'bongro', image: '../img/tk1.jpg'},
    {id: 83, name: 'Quần Bulls', price: 510000, category: 'quan', sport: 'bongro', image: '../img/tk1.jpg'},
    {id: 84, name: 'Quần Warriors', price: 520000, category: 'quan', sport: 'bongro', image: '../img/tk1.jpg'},
    {id: 85, name: 'Quần Chạy Bộ Nike', price: 310000, category: 'quan', sport: 'chaybo', image: '../img/tk1.jpg'},
    {id: 86, name: 'Quần Chạy Bộ Adidas', price: 290000, category: 'quan', sport: 'chaybo', image: '../img/tk1.jpg'},
    {id: 87, name: 'Quần Chạy Bộ Puma', price: 300000, category: 'quan', sport: 'chaybo', image: '../img/tk1.jpg'},
    {id: 88, name: 'Quần Chạy Bộ Asics', price: 340000, category: 'quan', sport: 'chaybo', image: '../img/tk1.jpg'},
    {id: 89, name: 'Quần Chạy Bộ New Balance', price: 350000, category: 'quan', sport: 'chaybo', image: '../img/tk1.jpg'},
    {id: 90, name: 'Quần Chạy Bộ Saucony', price: 330000, category: 'quan', sport: 'chaybo', image: '../img/tk1.jpg'},
    {id: 91, name: 'Quần Tập Gym Nike', price: 340000, category: 'quan', sport: 'tapgym', image: '../img/tk1.jpg'},
    {id: 92, name: 'Quần Tập Gym Adidas', price: 320000, category: 'quan', sport: 'tapgym', image: '../img/tk1.jpg'},
    {id: 93, name: 'Quần Tập Gym Puma', price: 330000, category: 'quan', sport: 'tapgym', image: '../img/tk1.jpg'},
    {id: 94, name: 'Quần Tập Gym Under Armour', price: 360000, category: 'quan', sport: 'tapgym', image: '../img/tk1.jpg'},
    {id: 95, name: 'Quần Tập Gym Reebok', price: 310000, category: 'quan', sport: 'tapgym', image: '../img/tk1.jpg'},
    {id: 96, name: 'Quần Tập Gym Lululemon', price: 420000, category: 'quan', sport: 'tapgym', image: '../img/tk1.jpg'},
    {id: 97, name: 'Quần Đạp Xe Nike', price: 450000, category: 'quan', sport: 'dapxe', image: '../img/tk1.jpg'},
    {id: 98, name: 'Quần Đạp Xe Adidas', price: 420000, category: 'quan', sport: 'dapxe', image: '../img/tk1.jpg'},
    {id: 99, name: 'Quần Đạp Xe Shimano', price: 480000, category: 'quan', sport: 'dapxe', image: '../img/tk1.jpg'},
    {id: 100, name: 'Quần Đạp Xe Puma', price: 440000, category: 'quan', sport: 'dapxe', image: '../img/tk1.jpg'},
    {id: 101, name: 'Quần Đạp Xe Trek', price: 460000, category: 'quan', sport: 'dapxe', image: '../img/tk1.jpg'},
    {id: 102, name: 'Quần Đạp Xe Giant', price: 470000, category: 'quan', sport: 'dapxe', image: '../img/tk1.jpg'},
    {id: 103, name: 'Quần Cầu Lông Yonex', price: 380000, category: 'quan', sport: 'caulong', image: '../img/tk1.jpg'},
    {id: 104, name: 'Quần Cầu Lông Victor', price: 360000, category: 'quan', sport: 'caulong', image: '../img/tk1.jpg'},
    {id: 105, name: 'Quần Cầu Lông Li-Ning', price: 340000, category: 'quan', sport: 'caulong', image: '../img/tk1.jpg'},
    {id: 106, name: 'Quần Cầu Lông Apacs', price: 320000, category: 'quan', sport: 'caulong', image: '../img/tk1.jpg'},
    {id: 107, name: 'Quần Cầu Lông Kawasaki', price: 400000, category: 'quan', sport: 'caulong', image: '../img/tk1.jpg'},
    {id: 108, name: 'Quần Cầu Lông Carlton', price: 380000, category: 'quan', sport: 'caulong', image: '../img/tk1.jpg'},
    
    // ===== GIÀY (109-144) =====
    {id: 109, name: 'Giày Bóng Đá Nike', price: 620000, category: 'giay', sport: 'bongda', image: '../img/tk1.jpg'},
    {id: 110, name: 'Giày Bóng Đá Adidas', price: 600000, category: 'giay', sport: 'bongda', image: '../img/tk1.jpg'},
    {id: 111, name: 'Giày Bóng Đá Puma', price: 580000, category: 'giay', sport: 'bongda', image: '../img/tk1.jpg'},
    {id: 112, name: 'Giày Mercurial', price: 710000, category: 'giay', sport: 'bongda', image: '../img/tk1.jpg'},
    {id: 113, name: 'Giày Copa', price: 680000, category: 'giay', sport: 'bongda', image: '../img/tk1.jpg'},
    {id: 114, name: 'Giày Nemeziz', price: 690000, category: 'giay', sport: 'bongda', image: '../img/tk1.jpg'},
    {id: 115, name: 'Giày Bóng Rổ LeBron', price: 700000, category: 'giay', sport: 'bongro', image: '../img/tk1.jpg'},
    {id: 116, name: 'Giày Air Jordan', price: 750000, category: 'giay', sport: 'bongro', image: '../img/tk1.jpg'},
    {id: 117, name: 'Giày Kyrie', price: 720000, category: 'giay', sport: 'bongro', image: '../img/tk1.jpg'},
    {id: 118, name: 'Giày Kobe', price: 760000, category: 'giay', sport: 'bongro', image: '../img/tk1.jpg'},
    {id: 119, name: 'Giày Harden', price: 740000, category: 'giay', sport: 'bongro', image: '../img/tk1.jpg'},
    {id: 120, name: 'Giày Durant', price: 730000, category: 'giay', sport: 'bongro', image: '../img/tk1.jpg'},
    {id: 121, name: 'Giày Chạy Bộ Nike', price: 560000, category: 'giay', sport: 'chaybo', image: '../img/tk1.jpg'},
    {id: 122, name: 'Giày Chạy Bộ Adidas', price: 550000, category: 'giay', sport: 'chaybo', image: '../img/tk1.jpg'},
    {id: 123, name: 'Giày Chạy Bộ Saucony', price: 580000, category: 'giay', sport: 'chaybo', image: '../img/tk1.jpg'},
    {id: 124, name: 'Giày New Balance', price: 600000, category: 'giay', sport: 'chaybo', image: '../img/tk1.jpg'},
    {id: 125, name: 'Giày Chạy Bộ Puma', price: 570000, category: 'giay', sport: 'chaybo', image: '../img/tk1.jpg'},
    {id: 126, name: 'Giày ASICS', price: 610000, category: 'giay', sport: 'chaybo', image: '../img/tk1.jpg'},
    {id: 127, name: 'Giày Tập Gym Nike', price: 440000, category: 'giay', sport: 'tapgym', image: '../img/tk1.jpg'},
    {id: 128, name: 'Giày Adidas Climacool', price: 450000, category: 'giay', sport: 'tapgym', image: '../img/tk1.jpg'},
    {id: 129, name: 'Giày Tập Gym Puma', price: 460000, category: 'giay', sport: 'tapgym', image: '../img/tk1.jpg'},
    {id: 130, name: 'Giày Reebok Crossfit', price: 480000, category: 'giay', sport: 'tapgym', image: '../img/tk1.jpg'},
    {id: 131, name: 'Giày Nike Air Zoom', price: 500000, category: 'giay', sport: 'tapgym', image: '../img/tk1.jpg'},
    {id: 132, name: 'Giày Lululemon', price: 520000, category: 'giay', sport: 'tapgym', image: '../img/tk1.jpg'},
    {id: 133, name: 'Giày Dã Ngoại Salomon', price: 620000, category: 'giay', sport: 'dangoai', image: '../img/tk1.jpg'},
    {id: 134, name: 'Giày Merrell', price: 610000, category: 'giay', sport: 'dangoai', image: '../img/tk1.jpg'},
    {id: 135, name: 'Giày Adidas Terrex', price: 630000, category: 'giay', sport: 'dangoai', image: '../img/tk1.jpg'},
    {id: 136, name: 'Giày The North Face', price: 650000, category: 'giay', sport: 'dangoai', image: '../img/tk1.jpg'},
    {id: 137, name: 'Giày Columbia', price: 600000, category: 'giay', sport: 'dangoai', image: '../img/tk1.jpg'},
    {id: 138, name: 'Giày Keen', price: 640000, category: 'giay', sport: 'dangoai', image: '../img/tk1.jpg'},
    {id: 139, name: 'Giày Vans', price: 380000, category: 'giay', sport: 'casual', image: '../img/tk1.jpg'},
    {id: 140, name: 'Giày Converse', price: 400000, category: 'giay', sport: 'casual', image: '../img/tk1.jpg'},
    {id: 141, name: 'Giày Timberland', price: 420000, category: 'giay', sport: 'casual', image: '../img/tk1.jpg'},
    {id: 142, name: 'Giày Skechers', price: 390000, category: 'giay', sport: 'casual', image: '../img/tk1.jpg'},
    {id: 143, name: 'Giày DC Shoes', price: 410000, category: 'giay', sport: 'casual', image: '../img/tk1.jpg'},
    {id: 144, name: 'Giày Lacoste', price: 430000, category: 'giay', sport: 'casual', image: '../img/tk1.jpg'},
    
    // ===== PHỤ KIỆN (145-180) =====
    {id: 145, name: 'Bóng Đá FIFA', price: 280000, category: 'phukien', sport: 'bong', image: '../img/tk1.jpg'},
    {id: 146, name: 'Bóng Chuyền', price: 320000, category: 'phukien', sport: 'bong', image: '../img/tk1.jpg'},
    {id: 147, name: 'Bóng Rổ', price: 300000, category: 'phukien', sport: 'bong', image: '../img/tk1.jpg'},
    {id: 148, name: 'Vợt Cầu Lông', price: 650000, category: 'phukien', sport: 'bong', image: '../img/tk1.jpg'},
    {id: 149, name: 'Vợt Tennis', price: 600000, category: 'phukien', sport: 'bong', image: '../img/tk1.jpg'},
    {id: 150, name: 'Gậy Golf', price: 800000, category: 'phukien', sport: 'bong', image: '../img/tk1.jpg'},
    {id: 151, name: 'Balo Nike', price: 450000, category: 'phukien', sport: 'tui', image: '../img/tk1.jpg'},
    {id: 152, name: 'Balo Adidas', price: 440000, category: 'phukien', sport: 'tui', image: '../img/tk1.jpg'},
    {id: 153, name: 'Túi Thể Thao', price: 380000, category: 'phukien', sport: 'tui', image: '../img/tk1.jpg'},
    {id: 154, name: 'Balo Puma', price: 460000, category: 'phukien', sport: 'tui', image: '../img/tk1.jpg'},
    {id: 155, name: 'Balo The North Face', price: 520000, category: 'phukien', sport: 'tui', image: '../img/tk1.jpg'},
    {id: 156, name: 'Túi Xách Thể Thao', price: 390000, category: 'phukien', sport: 'tui', image: '../img/tk1.jpg'},
    {id: 157, name: 'Băng Cuốn Tay', price: 120000, category: 'phukien', sport: 'baoho', image: '../img/tk1.jpg'},
    {id: 158, name: 'Bảo Vệ Cổ Chân', price: 150000, category: 'phukien', sport: 'baoho', image: '../img/tk1.jpg'},
    {id: 159, name: 'Băng Gối', price: 130000, category: 'phukien', sport: 'baoho', image: '../img/tk1.jpg'},
    {id: 160, name: 'Bảo Vệ Khuỷu Tay', price: 140000, category: 'phukien', sport: 'baoho', image: '../img/tk1.jpg'},
    {id: 161, name: 'Băng Lưng', price: 160000, category: 'phukien', sport: 'baoho', image: '../img/tk1.jpg'},
    {id: 162, name: 'Quần Vớ Kín', price: 170000, category: 'phukien', sport: 'baoho', image: '../img/tk1.jpg'},
    {id: 163, name: 'Vớ Cotton', price: 80000, category: 'phukien', sport: 'vo', image: '../img/tk1.jpg'},
    {id: 164, name: 'Vớ Chạy Bộ', price: 100000, category: 'phukien', sport: 'vo', image: '../img/tk1.jpg'},
    {id: 165, name: 'Vớ Nén Lực', price: 120000, category: 'phukien', sport: 'vo', image: '../img/tk1.jpg'},
    {id: 166, name: 'Găng Tay Gym', price: 140000, category: 'phukien', sport: 'vo', image: '../img/tk1.jpg'},
    {id: 167, name: 'Găng Tay Bóng Đá', price: 180000, category: 'phukien', sport: 'vo', image: '../img/tk1.jpg'},
    {id: 168, name: 'Găng Tay Ấm', price: 160000, category: 'phukien', sport: 'vo', image: '../img/tk1.jpg'},
    {id: 169, name: 'Thảm Yoga', price: 350000, category: 'phukien', sport: 'yoga', image: '../img/tk1.jpg'},
    {id: 170, name: 'Dây Kéo Yoga', price: 200000, category: 'phukien', sport: 'yoga', image: '../img/tk1.jpg'},
    {id: 171, name: 'Tạ Tay', price: 300000, category: 'phukien', sport: 'yoga', image: '../img/tk1.jpg'},
    {id: 172, name: 'Tạ Kettlebell', price: 400000, category: 'phukien', sport: 'yoga', image: '../img/tk1.jpg'},
    {id: 173, name: 'Con Lăn Foam', price: 280000, category: 'phukien', sport: 'yoga', image: '../img/tk1.jpg'},
    {id: 174, name: 'Khối Yoga', price: 220000, category: 'phukien', sport: 'yoga', image: '../img/tk1.jpg'},
    {id: 175, name: 'Khăn Thể Thao', price: 80000, category: 'phukien', sport: 'khac', image: '../img/tk1.jpg'},
    {id: 176, name: 'Bình Nước', price: 150000, category: 'phukien', sport: 'khac', image: '../img/tk1.jpg'},
    {id: 177, name: 'Đồng Hồ Thể Thao', price: 600000, category: 'phukien', sport: 'khac', image: '../img/tk1.jpg'},
    {id: 178, name: 'Tai Nghe Bluetooth', price: 400000, category: 'phukien', sport: 'khac', image: '../img/tk1.jpg'},
    {id: 179, name: 'Túi Đựng Giày', price: 180000, category: 'phukien', sport: 'khac', image: '../img/tk1.jpg'},
    {id: 180, name: 'Bóp Tiền Thể Thao', price: 120000, category: 'phukien', sport: 'khac', image: '../img/tk1.jpg'}
];
